databaseChangeLog:
  - changeSet:
      id: 1669819669895-7
      author: Anton (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_products
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: description
                  type: VARCHAR(255)
              - column:
                  constraints:
                    nullable: false
                  name: price
                  type: DECIMAL
              - column:
                  constraints:
                    nullable: false
                  name: duration
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: create_date
                  type: DATETIME
              - column:
                  name: last_update_date
                  type: DATETIME
            tableName: products
  - changeSet:
      id: 1669819669895-17
      author: Anton (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addUniqueConstraint:
            columnNames: id
            constraintName: uc_products_id
            tableName: products
  - changeSet:
      id: 1669819669895-18
      author: Anton (generated)
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - addUniqueConstraint:
            columnNames: name
            constraintName: uc_products_name
            tableName: products

